$(document).ready(function(){
    var gauge = new RadialGauge({
        renderTo: 'speedometer',
        width: 470,
        height: 470,
        title: false,
        value: 0,
        minValue: 0 ,
        maxValue: 180,
        majorTicks:[0,20,40,60,80,100,120,140,160,180],
        minorTicks:"2",
        strokeTicks: true,
        highlights:[{ "from": 160, "to": 180, "color": "darkRed" }],
        colorPlate:"transparent",
        colorMajorTicks:"#0088ff",
        colorMinorTicks:"#0088ff",
        colorNumbers:"#0088ff",
        colorNeedle:"rgba(240, 128, 128, 1)",
        needleCircleSize:"9",
        needleCircleOuter:true,
        needleCircleInner:false,
        colorNeedleShadowUp:"red",
        colorNeedleShadowDown:"red",
        colorNeedleCircleOuter:"black",
        colorNeedleCircleOuterEnd:"black",
        valueBox:false,
        animationRule:"linear",
        animationDuration: 500,
        fontNumbers:"Aldrich",
        animatedValue:true,
        needleType:"arrow",
        needleShadow:true,
        startAngle: 55,
        ticksAngle: 250,
        borders:true,
        colorBorderOuter:"transparent",
        colorBorderOuterEnd:"transparent",
        colorBorderMiddle:"transparent",
        colorBorderMiddleEnd:"transparent",
        colorBorderInner:"#0088ff",
        colorBorderInnerEnd:"transparent",
        colorBarProgress: "white",
        colorBar: "transparent",
        barWidth: "2",
        barShadow: "0"
    }).draw();

    gauge.value = 120;
    gauge.draw();
});